baseURL = "https://hajimetsuchiya.github.io/"
languageCode = "en-us"
title = "勝たんしか！！"
theme = "ananke"
contentDir = "post"
disableKinds = ["RSS","sitemap"]
publishDir = "docs"
[taxonomies]
tag = "tags"
